<?php
/**
 * @var \Yaroslav\RegularCustomer\Block\Product\View\DiscountRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
?>
 <div class="ya-roslav-regular-customer-request">
    <form class="form"
          id="ya-roslav-regular-customer-form"
          action="/errors/404.php"
          onsubmit="return false;"
          method="post"
          data-mage-init='{"Yaroslav_RegularCustomer_form":{
              "action": "<?= $escaper->escapeHtmlAttr($block->getUrl('yaroslav_regular_customer/index/request')) ?>"
          }}'
    >
        <fieldset class="fieldset">
            <br/>
            <div class="field name required">
                <label class="label" for="name">
                    <span><?= $escaper->escapeHtml(__('Name')) ?></span>
                </label>
                <div class="control">
                    <input name="name"
                           title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"
                    />
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email">
                    <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                </label>
                <div class="control">
                    <input name="email"
                           title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"
                    />
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden"
                       name="product_id"
                       value="<?= $escaper->escapeHtmlAttr((int) $product->getId()) ?>"
                />
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Send Request')) ?>"
                        class="action submit primary"
                >
                    <span><?= $escaper->escapeHtml(__('Send Request')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
