<?php
/**
 * @var \Yaroslav\RegularCustomer\Block\Product\View\DiscountRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
// Show form in modal window by default
if ($block->hasData('is_modal')) {
    $isModal = $block->getData('is_modal') ? 'true' : 'false';
} else {
    $isModal = 'true';
}
?>
<div class="ya-roslav-regular-customer-form" data-bind="scope: 'regularCustomerRequestForm'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "regularCustomerRequestForm": {
                        "component": "Yaroslav_RegularCustomer_form"
                    }
                }
            }
        }
    }
</script>
